### ISSUE TITLE
A missing file of BOLD5000

### ISSUE THREAD

**Issue by Chopinote** [naiq/LEA#1]
Hi authors,

Thank you so much for your excellent work on this paper! I have a couple of questions and would appreciate your clarification.

I just found that there might be a missing file in `./src/dataset.py`:

```python
def create_BOLD5000_CLIP_dataset(path='../../../data/BOLD5000', patch_size=16, image_size=256, image_norm=False, random_flip=False,
            drop_rate=0, subjects=['CSI1', 'CSI2', 'CSI3', 'CSI4'], include_nonavg_test=False, clip_name='', clip_ckpt='', clip_cache=''):
    roi_list = ['EarlyVis', 'LOC', 'OPA', 'PPA', 'RSC']
    fmri_path = os.path.join(path, 'BOLD5000_GLMsingle_ROI_betas/py')
    img_path = os.path.join(path, 'BOLD5000_Stimuli')
    imgs_dict = np.load(os.path.join(img_path, 'Scene_Stimuli/Presented_Stimuli/img_dict_label.npy'),allow_pickle=True).item()
    caption_dict = np.load(os.path.join(img_path, 'Scene_Stimuli/Presented_Stimuli/caption_dict.npy'),allow_pickle=True).item()
    repeated_imgs_list = np.loadtxt(os.path.join(img_path, 'Scene_Stimuli', 'repeated_stimuli_113_list.txt'), dtype=str)
```

1. I didn't find the file 'Scene_Stimuli/Presented_Stimuli/caption_dict.npy' at the repository of MinD-Vis.

2. May I ask if 'Scene_Stimuli/Presented_Stimuli/img_dict_label.npy' is the same as 'Scene_Stimuli/Presented_Stimuli/img_dict.npy' of MinD-Vis?

Here I attached a file structure of MinD-Vis for your reference. Thanks a lot for your clarification!
<img width="494" alt="Screenshot 2024-12-08 at 20 59 21" src="https://github.com/user-attachments/assets/247a5f95-fb23-4f57-96c4-eb35446874da">

**Comment by naiq** [comment]
Thanks for your interest!
These two files contain additional categories and caption information for visual stimuli, but are not used in this work. Sorry I forgot to delete them when cleaning up the code. I have fixed this issue in the latest [commit](https://github.com/naiq/lea/commit/f75c582).

**Comment by Chopinote** [comment]
Thank you a lot for your help!
